name: Daily Security Pipeline

on:
  schedule:
    - cron: '0 3 * * *' # Tous les jours à 3h du matin
  workflow_dispatch:

jobs:
  DependenciesAnalysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download OSV Scanner v2.0.2
        run: |
          curl -sSL https://github.com/google/osv-scanner/releases/download/v2.0.2/osv-scanner_linux_amd64 -o osv-scanner
          chmod +x osv-scanner
          sudo mv osv-scanner /usr/local/bin/

      - name: Run OSV Scanner
        run: |
          osv-scanner --lockfile=package-lock.json --format=sarif > osv.sarif || echo "No SARIF output"

      - name: Upload SARIF report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: osv.sarif

  SourceCodeAnalysis:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run semgrep (Java ruleset)
        run: semgrep --config p/java --sarif --output semgrep.sarif

      - name: Upload SARIF report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif

