name: Daily Security Pipeline

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

permissions:
  contents: read
  actions: read

jobs:
  DependenciesAnalysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download OSV Scanner v2.0.2
        run: |
          curl -sSL https://github.com/google/osv-scanner/releases/download/v2.0.2/osv-scanner_linux_amd64 -o osv-scanner
          chmod +x osv-scanner
          sudo mv osv-scanner /usr/local/bin/

      - name: Run OSV Scanner
        run: |
          if [ -f package-lock.json ]; then
            osv-scanner --lockfile=package-lock.json --format=sarif > osv.sarif
          else
            echo '{"version": "2.1.0", "runs": []}' > osv.sarif
          fi

      - name: Save SARIF result
        uses: actions/upload-artifact@v2
        with:
          name: osv-sarif
          path: osv.sarif



