name: Daily Security Pipeline

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  security-events: write

jobs:
  osv-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Run OSV Scanner on gradle.lockfile
        uses: google/osv-scanner-action/osv-scanner-action@8dded7155905cd666190a12dc9997000e58d163d
        with:
          scan-args: >-
            --output=osv-results.sarif
            --format=sarif
            app/gradle.lockfile
        continue-on-error: true

      - name: Upload OSV SARIF to Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: osv-results.sarif

  semgrep-scan:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Semgrep on VulnerableController
        run: semgrep --config p/java app/src/main/java/dev/xdbe/booking/controller/VulnerableController.java --sarif --output=semgrep-results.sarif

      - name: Upload Semgrep SARIF to Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep-results.sarif

