name: Daily OSV Scan via Reusable Workflow

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  osv-scan:
    uses: google/osv-scanner-action/.github/workflows/scan.yml@8dded7155905cd666190a12dc9997000e58d163d
    with:
      scan-args: |
        -r
        ./
      results-file-name: osv.sarif
      upload-sarif: false
      fail-on-vuln: false

