name: Daily Security Pipeline

on:
  schedule:
    - cron: '0 3 * * *' 
  workflow_dispatch:

jobs:
  DependenciesAnalysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run OSV Scanner
        uses: google/osv-scanner-action@v1

      - name: Upload SARIF report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif

  SourceCodeAnalysis:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run semgrep (Java ruleset)
        run: semgrep --config p/java --sarif --output semgrep.sarif

      - name: Upload SARIF report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: semgrep.sarif

