name: Daily Security Pipeline

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

permissions:
  contents: read
  actions: read

jobs:
  DependenciesAnalysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run OSV Scanner
        uses: google/osv-scanner-action@v2.02
        with:
          scan-args: >-
            --lockfile=package-lock.json
            --format=sarif
            --output=osv.sarif

      - name: Print SARIF result
        run: cat osv.sarif

  SourceCodeAnalysis:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run semgrep (Java ruleset)
        run: semgrep --config p/java --sarif --output semgrep.sarif

      - name: Print SARIF result
        run: cat semgrep.sarif

